feature/1: Inversed_related_products
Uewek/magento2 pull request #2
Opened 2021-06-22 13:12 UTC by Uewek

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-06-23 08:17 UTC, ysapiga requested changes

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +    private $_linkedProductsFactory;
Не треба добавляти _ до полів класа

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +    private $productRepository;
Нема док блока

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +     * @throws \Magento\Framework\Exception\NoSuchEntityException
Цей тег добавляється тількти тоді якшо конкретно цей метод кидає ексепшн

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +    public function getProductById(int $id)
Цей метод тобі не потрібен. Іспользуй репозиторій напряму там де треба

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +class Extra extends Template
Приватні методи і змінні мають бути нижче публічних і протектед

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +        $relations = $this->_linkedProductsFactory->create();
це дуже затрантний метод. Ти загружаєш всю колекцію а потім береш тільки 3 елемента. Тре переробити.
твій запрос має бути шось типу SELECT FROM table_name WHERE linked_product_id = current_product LIMIT 3. Подумай як з допомогою колекцій це зробити. Передивись класи колекцій які в них є методи і шо вони роблять.

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +            $products[] = $this->getProductById($inversedRelationId);
загружати продукти по 1му всередині цикла погана ідея. Використовуй колекцію з правильними фільтрами

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +        $result = $this->config->isEnabled();
return $this->config->isEnabled();
нашо тобі та проміжна змінна?

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Model/LinkedProducts.php
> +class LinkedProducts extends AbstractModel implements IdentityInterface
Для чого цей клас? Де ти його використовуєш?

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Model/ResourceModel/LinkedProducts.php
> +class LinkedProducts extends AbstractDb
Для чого ти створив цю ресурс модель?

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Model/ResourceModel/LinkedProducts/Collection.php
> +class Collection extends AbstractCollection
Для чого новий клас колекції для цьої таблиці? Чим тобі існуючі класи не підходять?

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/etc/adminhtml/system.xml
> +                <field id="enable" translate="label" type="select" sortOrder="1"
enable шо? Давай більш зрозумілі імена філдам

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/etc/module.xml
> +    <module name="Study_InversedRelatedProducts" setup_version="1.0.1"/>
додай залежності в модуль.` <sequence></sequence>`

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/view/frontend/layout/catalog_product_view_type_simple.xml
> +    <move element="product.info.inversedrelations" destination="product.info.main" after="product.info.price"/>
Для чого робити мув блока?

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/view/frontend/templates/product/view/extra.phtml
> +<?php if (count($inversedRelatedProductsArray) != 0 && $block->canShowInversedProducts()): ?>
$block->canShowInversedProducts() має бути 1м в умові
count($inversedRelatedProductsArray) != 0 можна замінити на !empty($inversedRelatedProductsArray)

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/etc/adminhtml/system.xml
> +            <resource>Study_InversedRelatedProducts::inversedRelatedProducts_configuration</resource>
Ти не добавив acl. Можеш удалити воно іта кпрацювати не буде

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/etc/adminhtml/system.xml
> +            <class>separator-top</class>
Це лишнє

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Model/Config.php
> +    private $scopeConfig;
док блок упущений

2021-06-23 08:17 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +
`declare(strict_types=1);` поправ всюди де невистачає його

2021-06-24 06:55 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +
+

2021-06-24 06:57 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +class Extra extends Template
+

2021-06-24 06:58 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +    private $_linkedProductsFactory;
+

2021-06-24 07:05 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +     * @throws \Magento\Framework\Exception\NoSuchEntityException
+

2021-06-24 07:05 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +    public function getProductById(int $id)
+

2021-06-24 07:06 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +        $result = $this->config->isEnabled();
+

2021-06-24 07:07 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Model/Config.php
> +    private $scopeConfig;
+

2021-06-24 07:08 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Model/LinkedProducts.php
> +class LinkedProducts extends AbstractModel implements IdentityInterface
він використовується в коллекції

2021-06-24 07:08 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Model/ResourceModel/LinkedProducts.php
> +class LinkedProducts extends AbstractDb
вона нужна коллекції

2021-06-24 15:40 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/etc/adminhtml/system.xml
> +            <class>separator-top</class>
+

2021-06-24 15:40 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/etc/adminhtml/system.xml
> +            <resource>Study_InversedRelatedProducts::inversedRelatedProducts_configuration</resource>
+

2021-06-24 15:42 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/etc/adminhtml/system.xml
> +                <field id="enable" translate="label" type="select" sortOrder="1"
+

2021-06-24 15:44 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/etc/module.xml
> +    <module name="Study_InversedRelatedProducts" setup_version="1.0.1"/>
+

2021-06-25 08:44 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Model/ConfigInterface.php
> +    const XML_PATH_ENABLED = 'catalog/frontend/enableInversedRelations';
в конфігах не використовуєм камелКейс тут використовуєм снейк_кейс

2021-06-25 08:44 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/etc/module.xml
> +            <module name="Magento_Catalog"/>
Де залежності?

2021-06-25 08:44 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +        $limitedCollection->addAttributeToSelect('*');
тобі не треба всі атрибути. Це Важкий запит. Добав в селект тільки ті атрибути які тобі треба

2021-06-25 08:44 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +        return $limitedCollection;
перед return завжи пусту строку робиш

2021-06-25 08:44 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +        $limitedCollection->setPageSize(3);
+ setCurrentPage() or
$collection->getSelect()->limit(3)

2021-06-25 08:44 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +     * @return \Magento\Catalog\Model\ResourceModel\Product\Collection
винеси в юзи

2021-06-25 08:44 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +    public function getLimitedProductCollection()
перейменуй мето і зміні на підхдящі імена InveresedRealtedProductsColection

2021-06-25 08:44 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +        parent::__construct($context);
перед визовом  parent так само як і return має бути пуста строка

2021-06-25 08:57 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Model/ConfigInterface.php
> +    const XML_PATH_ENABLED = 'catalog/frontend/enableInversedRelations';
1

2021-06-25 09:14 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +        $limitedCollection->addAttributeToSelect('*');
1

2021-06-25 09:14 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +    public function getLimitedProductCollection()
1

2021-06-25 09:15 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +     * @return \Magento\Catalog\Model\ResourceModel\Product\Collection
1

2021-06-25 09:16 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +        parent::__construct($context);
1

2021-06-25 09:16 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +        $limitedCollection->setPageSize(3);
1

2021-06-25 09:45 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +        parent::__construct($context);
1

2021-06-25 09:45 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +     * @return \Magento\Catalog\Model\ResourceModel\Product\Collection
1

2021-06-25 09:46 UTC, Uewek commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +    public function getLimitedProductCollection()
1

2021-06-25 14:11 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +    public function getInveresedRealtedProductsColection()
Добав ретурн тайп

2021-06-25 14:11 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +
тут не тре пусту строку

2021-06-25 14:11 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +
пуста строка перед ретурном тільки тоді якшо це не єдіснственна строка в методі

2021-06-25 14:11 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/Block/Product/View/Extra.php
> +
Удали лишні пусті строки

2021-06-25 14:11 UTC, ysapiga commented on app/code/Study/InversedRelatedProducts/etc/adminhtml/system.xml
> +                <label>Storefront</label>
Нашо ти вказав цю лейбу?

2021-06-25 19:21 UTC, merged